



base:
  logger_file_path: "Logs/main.log"
  base_url: "http://localhost:8991"
  date_start: 20220101
  days: 7
  flink:
    - job_name: "cohort"
      enable: false
      pns:
        - cny
        - hy
      channels:
        - cny_01
        - cny_02
    - job_name: "realtime"
      enable: false
      pns:
        - cny
        - hy
      channels:
        - cny_01
        - cny_02
    - job_name: "repetition"
      enable: false
      pns:
        - cny
        - hy
      channels:
        - cny_01
        - cny_02








