spring:
  config:
    import:
      - application-custom.yaml
#      - application-datasource.yaml
#      - application-flyway.yaml
      - application-log.yaml
      - application-spring.yaml
#      - application-mq.yaml
#      - application-redis.yaml


