

---
spring:
  config:
    activate:
      on-profile: suyh

flink:
  job:
    queue:
      submit:
        flink-web-host: "localhost"
        flink-web-port: 8991
        flink-home: "/home/flink_batch/flink/flink-1.18.0"
        dates-start: 20240117
        dates-last: 20240117
        pns: "inr,cny,brl,pkr,hy"
        restart-job-number: 30
        # 并行作业数量
        parallelism-job: 2
        jobs:
          - job-name: cohort
            enabled: true
            jar-path: "${flink.job.queue.submit.flink-home}/job-jar/flink-cohort-job-3.2.0.jar"
          - job-name: realtime
            enabled: true
            jar-path: "${flink.job.queue.submit.flink-home}/job-jar/realtime-trend-job-3.2.0.jar"
          - job-name: repetition
            enabled: true
            jar-path: "${flink.job.queue.submit.flink-home}/job-jar/cdap-repetition-job-3.2.0.jar"


