#
#
#
#---
#spring:
#  config:
#    activate:
#      on-profile: suyh
#
#
#  rabbitmq:
#    host: 192.168.8.143
#    port: 5672
#    username: admin
#    password: adminadmin
#    virtualHost: /suyhCdapFlink
#
#
#
