logging:
  level:
    root: info
  file:
    name: /tmp/flink_job_queue_submit/logs/info.log
  logback:
    rollingpolicy:
      file-name-pattern: /tmp/flink_job_queue_submit/logs/%d{yyyy-MM-dd}/info.%03i.log

---
spring:
  config:
    activate:
      on-profile: suyh



