#spring:
#  datasource:
#    dynamic:
#      enabled: true
#      primary: "flink-cds"
#
#
#---
#spring:
#  config:
#    activate:
#      on-profile: suyh
#
#
#  datasource:
#    hikari:
#      flink-cds:
#        jdbc-url: jdbc:mysql://192.168.8.143:3306/suyh_cdap_cds?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&rewriteBatchedStatements=true
#        username: suyh_cdap_cds
#        password: suyh_cdap_cds
#      flink-pg-cdap:
#        jdbc-url: jdbc:postgresql://192.168.8.143:5432/suyh_pg_cdap_cds?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
#        username: suyh_pg_cdap_cds
#        password: suyh_pg_cdap_cds
#        driver-class-name: org.postgresql.Driver
#
#
